# Generated by Django 2.2.1 on 2019-05-21 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acordo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acordo', models.DateField()),
                ('valor_original', models.FloatField()),
                ('valor_acordado', models.FloatField()),
                ('desconto', models.FloatField()),
            ],
            options={
                'db_table': 'acordo',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('idade', models.IntegerField()),
                ('altura', models.FloatField()),
                ('profissao', models.CharField(max_length=200, null=True)),
                ('salario', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_parcela', models.FloatField()),
                ('data_vencimento', models.DateField()),
                ('valor_pago', models.FloatField(null=True)),
                ('data_pagamento', models.DateField(null=True)),
                ('status_parcela', models.CharField(default='Não Paga', max_length=200)),
                ('acordo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Acordo')),
            ],
        ),
        migrations.AddField(
            model_name='acordo',
            name='contratante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Cliente'),
        ),
    ]
