# Generated by Django 2.2.1 on 2019-05-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='salario',
            field=models.FloatField(null=True),
        ),
    ]
