from .clienteserializer import ClienteSerializer
from .clienteserializer import ClienteSerializerId
from .acordoserializer import AcordoListSerializer
from .acordoserializer import AcordoCreateSerializer
from .acordoserializer import ParcelaSerializer
