# Generated by Django 2.2.1 on 2019-05-21 13:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'agencia',
            },
        ),
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=200)),
                ('classificacao', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'cidade',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_contrato', models.CharField(max_length=200)),
                ('data_contrato', models.DateField(null=True)),
                ('valor_contrato', models.FloatField()),
                ('valor_corrigido', models.FloatField()),
                ('data_cadastro', models.DateField(verbose_name=datetime.datetime(2019, 5, 21, 13, 29, 25, 199527, tzinfo=utc))),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.Agencia')),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.Carteira')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.Cliente')),
            ],
            options={
                'db_table': 'contrato',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=200, null=True)),
                ('numero', models.IntegerField(null=True)),
                ('complemento', models.CharField(max_length=200, null=True)),
                ('cep', models.IntegerField(max_length=200, null=True)),
                ('bairro', models.CharField(max_length=200, null=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.Cidade')),
            ],
            options={
                'db_table': 'endereco',
            },
        ),
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=500, null=True)),
                ('marca', models.CharField(max_length=200, null=True)),
                ('placa', models.CharField(max_length=10, null=True)),
                ('renavam', models.CharField(max_length=200, null=True)),
                ('cor', models.CharField(max_length=200, null=True)),
                ('ano_fabricacao', models.IntegerField(null=True)),
                ('ano_modelo', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'garantia',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf_cnpj', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'pessoa',
            },
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualificacao', models.CharField(choices=[('HOT', 'HOT'), ('PESSOAL', 'PESSOAL'), ('PESSOA_RELACIONADA', 'PESSOA_RELACIONADA'), ('COMERCIAL', 'COMERCIAL')], max_length=40)),
                ('numero', models.CharField(max_length=40)),
                ('celular', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PessoaEndereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.Pessoa')),
                ('pessoa_endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.Endereco')),
            ],
            options={
                'db_table': 'pessoa_endereco',
            },
        ),
        migrations.CreateModel(
            name='ParcelaContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField()),
                ('data_cadastro', models.DateField(default=datetime.datetime(2019, 5, 21, 13, 29, 25, 200286, tzinfo=utc))),
                ('valor_parcela', models.FloatField()),
                ('valor_corrigido', models.FloatField(null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.Contrato')),
            ],
            options={
                'db_table': 'parcela_contrato',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('sigla', models.CharField(max_length=2, unique=True)),
                ('regiao', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('nome', 'sigla')},
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='ContratoGarantia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.Contrato')),
                ('garantia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.Garantia')),
            ],
            options={
                'db_table': 'contrato_garantia',
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.Endereco'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.Empresa'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.Estado'),
        ),
    ]
